---
- name: Установка программ и ярлыков на Windows 11
  hosts: windows
  gather_facts: false

  vars:
    programs:
      - name: "7-Zip"
        url: "https://www.7-zip.org/a/7z2301-x64.exe"
        dest_file: "C:\\Temp\\7z2301-x64.exe"
        install_path: "C:\\Program Files\\7-Zip\\7zFM.exe"
        args: "/S"
      - name: "Notepad++"
        url: "https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.6.4/npp.8.6.4.Installer.x64.exe"
        dest_file: "C:\\Temp\\npp-8.6.4.exe"
        install_path: "C:\\Program Files\\Notepad++\\notepad++.exe"
        args: "/S"
      - name: "PuTTY"
        url: "https://the.earth.li/~sgtatham/putty/0.82/w64/putty-64bit-0.82-installer.msi"
        dest_file: "C:\\Temp\\putty-0.82.msi"
        install_path: "C:\\Program Files\\PuTTY\\putty.exe"
        args: "/quiet"

  tasks:

    - name: Создать папку C:\Temp
      win_file:
        path: C:\Temp
        state: directory

    - name: Устанавливаем программы и создаём ярлыки по одной
      include_tasks: install_program.yml
      loop: "{{ programs }}"
      loop_control:
        loop_var: program


